version: '3.8'
x-common-variables: &common-variables
  MYSQL_DATABASE: messenger
  MYSQL_USER: dbuser
  MYSQL_PASSWORD: qweqweasd
services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports: 
      - "3030:3030"
      - "22:22"
    environment:
      - BACKEND_SERVER=host.docker.internal
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST_NAME=localhost
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
      args:
        REACT_APP_HOST_IP_ADDRESS: host.docker.internal
    ports:
      - "3050:80"

  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost


  messagingapi:
    build:
      dockerfile: Dockerfile
      context: "./messagingapi"
    ports:
      - 4001:4001
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - "8000:8080"
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db